# Generated by Django 4.1.7 on 2024-04-08 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=96)),
                ('razao_social', models.CharField(max_length=96)),
                ('name', models.CharField(max_length=96)),
                ('number', models.CharField(max_length=96)),
                ('date_lastsell', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representada', models.CharField(max_length=18)),
                ('valor_frete', models.FloatField(max_length=96)),
                ('valor_itens', models.FloatField(max_length=96)),
            ],
        ),
    ]
