# Generated by Django 4.1.7 on 2024-05-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=18)),
                ('descricao', models.FloatField(max_length=96)),
                ('medida', models.FloatField(max_length=96)),
                ('quantidade', models.CharField(max_length=18)),
                ('vlr_un', models.FloatField(max_length=96)),
                ('vlr_total', models.FloatField(max_length=96)),
            ],
        ),
    ]
