# Generated by Django 4.1.7 on 2024-05-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacoes', '0002_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='produto',
            name='medida',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.FloatField(max_length=18),
        ),
    ]
