# Generated by Django 4.1.7 on 2024-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacoes', '0004_representada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('cpf', models.IntegerField(max_length=96)),
                ('fullName', models.CharField(max_length=96)),
                ('numero', models.IntegerField(max_length=18)),
                ('endereco', models.CharField(max_length=96)),
                ('vendas', models.FloatField(max_length=18)),
                ('ticket', models.FloatField(max_length=96)),
                ('totalVendas', models.FloatField(max_length=18)),
            ],
        ),
    ]
