# Generated by Django 4.1.7 on 2024-06-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacoes', '0008_alter_representante_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='cnpj',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cpf',
            field=models.BigIntegerField(),
        ),
    ]
